name: test_ios
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  extended_image: ^9.0.7
  shimmer: ^3.0.0
  shared_preferences: ^2.3.3
  intl: ^0.18.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
